sass:
    load_paths:
        - _sass
        - node_modules

exclude: []

baseurl: ""



# Social icons
show_social_icons: true
github_username: timcknowles
twitter_username: knowlesarian


prose:
  rooturl: '_posts'
  siteurl: 'www.headandnecktrials.com/'
  relativeLinks: 'www.headandnecktrials.com/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Early"
              value: "early"
            - name: "Advanced"
              value: "advanced"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add anatomical site"
          placeholder: "Choose site"
          options:
            - name: "oral Cavity"
              value: "oral cavity"
            - name: "larynx"
              value: "larynx"
            - name: "hypopharynx"
              value: "hypopharynx"
            - name: "oropharnyx"
              value: "oropharnyx"
      - name: "title"
        field:
          element: "text"
          label: "Article title format = yyyy-mm-dd-title"
          placeholder: "Title"
          alterable: true
