sass:
    load_paths:
        - _sass
        - node_modules

exclude: []

baseurl: "/headandneckcancersite"



# Social icons
show_social_icons: true
github_username: timcknowles
twitter_username: knowlesarian
